version: 2

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
  disable:
    - asasalint
    - bidichk
    - clickhouselint
    - containedctx
    - depguard
    - err113
    - errchkjson
    - exhaustive
    - ginkgolinter
    - gocheckcompilerdirectives
    - ireturn
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - nakedret
    - wastedassign
run:
  timeout: 2m
